services:
  - type: web
    name: shuffllify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    autoDeploy: true 